runtimeverification/iele-semantics

- iele-syntax/iele-syntax.k
Without this change
log @a,@b,@c,@d=call @d()
could be parse as either
log @a,@b,
@c,@d=call @d()
or
log @a,@b,@c,@d
=call @d()
> Fix syntactic ambiguity

- KRYPTO.ml
Key recovery now returns an option. This makes `KRYPTO.ml` compile again just by assuming recovery succeeds.
> Fix KRYPTO.ml for newest secp256k1 version 0.3.2

- tangle.lua
It turns out table.unpack was added in 5.2 and the
pandoc distributed in Ubuntu 14.04 was built with 5.1
> Avoid lua-5.2-only function in tangle.lua

- .gitignore
- .gitmodules
- INSTALL.md
- compiler/README.md
- compiler/app/Main.hs
- compiler/compiler.cabal
- compiler/src/IeleDesugar.hs
- compiler/src/IeleInstructions.hs
- compiler/src/IeleParserImplementation.hs
- compiler/src/IelePrint.hs
- compiler/src/IeleTHUtil.hs
- compiler/src/IeleTypes.hs
- compiler/test/TestParser.hs
- iele-examples/erc20.iele
Now allows immediate arguments to any instruction, which
is compiled by loading the immediates into temporary registers.
Allow global definitions of named constants, which expand
into immediate values.
Add options to reprint the input, either immediately after parsing
or just before assembling.
> Support global definitions, immediates, output options

- iele-examples/README.md
Now suggests testing iele tests with iele-test target
and describes how to run individual tests, rather than
only suggesting `make test` or explicit shell loops over
the testcases.
> Change test instructions to use iele-test target

- Makefile
- ethereum.md
- iele-syntax.md
This should be enough to make kast work.
apaprently `kast` is looking for a `<MODULE>-PROGRAM-PARSING` and if it does not find one, it generates one including `ID-PROGRAM-PARSING` syntax which contains some token rules with higher precedence than ours.  That is why the `IeleName`s ended up being parsed as `Id`s and `kast` reported an error.
> Changes to make kast work

- Makefile
The secp256k1 opam package seems to still be in flux with respect to its public API.
We are fixing this to a specific version so that if it changes again, it will not break
new installs.
> Downgrade version of secp256k1 to install

- README.md
Updated README.md to point to iele-syntax.md as the starting point forr familiarizing with IELE.
> README.md update to point to iele-syntax.nd and Design.md

- iele.md
Previously a bug existed where if a contract called another contract and then reverted, the values returned to the parent contract contained the values returned by the nested contract call. This is obviously not the intended behavior, and so I created a fix for it.
> don't leak return values when we revert

- check-iele
- compiler/src/IeleAssembler.hs
- compiler/src/IeleDesugar.hs
- compiler/src/IeleInstructions.hs
- compiler/src/IeleParserImplementation.hs
- compiler/src/IelePrint.hs
- compiler/src/IeleTypes.hs
- data.md
- ethereum.md
- iele-binary.md
- iele-gas.md
- iele-node.md
- iele-syntax.md
- iele.md
- tests/iele/unit/fptr.iele
- tests/iele/unit/fptr.iele.json
- well-formedness.md
Per our previous discussion, this PR adds function pointers to IELE by allowing global function names anywhere an operand can be used in the assembler, and adding semantics for dynamic call targets computed from an integer function offset.
> Function pointers in IELE

- iele-syntax.md
This is useful for the plutus-to-iele translation since it makes debugging/postprocessing easier.
> iele-syntax: Added formatting attributes to common IELE constructs

- compiler/src/IeleAssembler.hs
- iele-binary.md
- tests/evm-to-iele/iele.ml
- tests/iele/ERC20/create.iele.json
- tests/iele/auction/create.iele.json
- tests/iele/forwarder/copycreate.iele.json
- tests/iele/forwarder/create.iele.json
- tests/iele/ill-formed/illFormed.iele.json
This PR adds a new opcode in the binary format (0x6b) that signifies start of a metadata stamp. The metadata stamp is a binary string of arbitrary length and contents that is being dropped from the IELE disassembler at loading time. I didn't include this opcode in the assembler since there is no way to add a metadata stamp to a textual iele program.
> Metadata stamp for binary representation.

- compiler/src/IeleAssembler.hs
- compiler/src/IeleInstructions.hs
- compiler/src/IeleParserImplementation.hs
- compiler/src/IelePrint.hs
- ethereum.md
- iele-binary.md
- iele-node.md
- iele.md
- tests/evm-to-iele/conversion.ml
- tests/evm-to-iele/iele.ml
- tests/iele/auction/create.iele.json
- tests/iele/ill-formed/illFormed2.iele.json
- well-formedness.md
Code that checks to make sure we can successfully disassemble the contract prior to actually trying to disassemble it.
This prevents crashes in cases where we previously had not given semantics, but also closes attack vectors where previously large immediate constants could have led to an improperly large amount of time spent trying to disassemble a maliciously constructed contract.
Fixes #121
Ready for review.
> Binary contract validator

- iele-syntax.md
Fixed an inaccuracy in the documentation for the `@init` function in `iele-syntax.md`
> Minor documentation fix for init function

- INSTALL.md
Two changes:
1. `caskroom/version` no longer exists. The new cask is named `versions`. Also `caskroom` is deprecated in favor of `homebrew`.
2. I didn't realize I was building from source rather than setting up a runtime environment, so when I hit `git submodule`, I stumbled that was the first clue I was supposed to be in a cloned repo.
> Corrections to install instructions.

- iele.md
In `### Expressions` section the `sub a,b` line is missing
> Added missing expressions to `iele.md`

- iele.md
Description mentioned "list of registers, but `revert` takes a single argument
> Fixed `revert` description in `iele.md`

- .gitmodules
- Makefile
- blockchaintest
- check-iele
- vmtest
I added KORE as a submodule in IELE. Notice it's in the folder `tests/ci/kore`; I am not sure this is the right choice, but I tried to mimic K which is in `tests/ci/rv-k`. 
The Makefile has been updated to provide the following: 
* `make haskell-deps`: builds the haskell backend 
* `make haskell`: compiles IELE to KORE, to be used with the Haskell backend.
> Add KORE submodule and update Makefile

- Makefile
- vmtest-haskell
Adding a simple script, similar to `vmtest`, that runs a IELE program on the Haskell backend. 
It's not fully functional/finished.
> Run in haskell backend

- vm/c/main.cpp
`set_gc_interval` was removed from the LLVM backend.
> Remove set_gc_interval

- .github/workflows/release.yml
This is required for runtimeverification/solidity#175 because the Solidity compiler depends on `iele-assemble`. This is the same process used for the K Framework release.
> Add Release workflow to create release.nix

- data.md
This fixes a regression introduced in the replacement of `WordStack` with `Bytes`.
The regression was introduced by the change found [here](https://github.com/runtimeverification/iele-semantics/commit/816c1c125fe1bb0f5621c98cc76787b07e747963#diff-8646165c2d354850965539efadf4790e50a9589382a98f1b5b2e07d54e62a15dR463).
The bug was introduced because the newer version failed to skip the first byte of the RLP encoded bytestring before decoding the next byte(s) into the length.
Fixes https://github.com/runtimeverification/iog-pm/issues/85
> Fix in the #loadLen helper

- iele.md
- tests/iele/danse/unit/exceptions.iele.json
This PR removes an artificial limitation on the semantics of the `bswap` instruction, namely the instruction now can be applied to a negative integer argument.
> fix for bswap instruction

- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/update.yml
- nix/kiele.nix
This PR is a fix for CI failures related to a new Nix release yesterday. It does two things:
* Bumps the github actions we use for nix (`install-nix`, `install-cachix`) to their newest versions.
* Pins Nix to 2.3.16 as a temporary fix, as 2.4 breaks on macos at the moment.
> Bump CI action versions, pin nix to 2.3.16
