gas.md

Dwight will remove PC in https://github.com/runtimeverification/iele-semantics/pull/14

Remove PC and rename TMESTAMP.

---

iele-examples/erc20.iele

Initial draft of ERC20 in IELE

erc20 draft added

---

.gitignore
.gitmodules
INSTALL.md
Makefile
blockchaintest
vmtest

Tested on a fresh Ubuntu 16.04.

Installation instructions

---

.gitmodules
INSTALL.md
Makefile
data.md
ethereum.md
iele-binary.md
iele-syntax.md
iele.md
krypto.md
tangle.lua

This should completely replace pandoc-tangle.

Untangle lua instead of pandoc-tangle

---

INSTALL.md

Added missing package dependencies.
Fixed working directory changes.

Various fixes in the installation instructions

---

INSTALL.md
Makefile

Fixes an issue reported by a user on the public iele channel. @theo25 please review.

fix bugs in install process

---

Makefile
iele-semantics-plugin/KRYPTO.ml
iele-semantics-plugin/MANTIS.ml
iele-semantics-plugin/META
iele-semantics-plugin/caching.ml
iele-semantics-plugin/threadLocal.ml
iele-semantics-plugin/threadLocal.mli
iele-semantics-plugin/world.ml
iele-semantics-plugin/world.mli
iele-vm/ieleNetworkServer.ml
iele-vm/ieleTestClient.ml
iele-vm/ieleVM.ml

Communication isn't tested at all, but the server listens when run.

Mantis client and server networking code

---

README.md

Update plugin submodule for usage messages in iele-vm

---

INSTALL.md
Makefile

Adds build system to build submodules recursively and refer to a submodule for the protobufs.

change build system and install instructions to build protobuf version

---

tests/iele/unit/selfdestruct.iele
tests/iele/unit/selfdestruct.iele.json

This should fix the issue @dfilaretti was having with the solidity selfdestruct end to end test.

Update plugin submodule and add test for selfdestruct

---

compiler/src/IeleAssembler.hs
compiler/src/IeleInstructions.hs
compiler/src/IeleParserImplementation.hs
compiler/src/IelePrint.hs
iele-binary.md
iele-gas.md
iele-syntax.md
iele.md
tests/iele/unit/calladdress.iele
tests/iele/unit/calladdress.iele.json
tests/iele/unit/fptr.iele
well-formedness.md

Adds an instruction that gets the function pointer of an external function from its name and an address.

Get function offset instruction

---

Makefile
compiler/src/IeleDesugar.hs
data.md
ethereum.md
iele-gas.md
iele-syntax.md
iele.md
tests/iele/unit/blockhash.iele
tests/iele/unit/blockhash.iele.json
tests/iele/unit/collision.iele
tests/iele/unit/collision.iele.json
tests/iele/unit/exceptions.iele
tests/iele/unit/exceptions.iele.json
tests/iele/unit/precompiled.iele
tests/iele/unit/precompiled.iele.json
tests/iele/unit/staticcall.iele
tests/iele/unit/wellFormed.iele
well-formedness.md

Ready for review.
Adds a variable to the Makefile that allows us to generate either K or OCAML coverage for the IELE semantics.
Also substantially improves coverage via dead code elimination and increased testing. 
K coverage report is here: https://office.runtimeverification.com/jenkins/job/iele-semantics-pull-request/cobertura
OCAML coverage report (not completely automated yet) is here: https://office.runtimeverification.com/sandbox/coverage/
Fixes #91 
Fixes #94 
Fixes #97

coverage tracking of iele semantics

---

data.md
ethereum.md
iele-binary.md
iele-node.md
well-formedness.md

update k submodule

---

data.md
ethereum.md
iele-gas.md
iele-syntax.md
iele.md
tests/iele/ERC20/approve_Caller-Zero.iele.json
tests/iele/ERC20/approve_Other-Zero.iele.json
tests/iele/ERC20/transfer_Caller-Zero.iele.json
tests/iele/ERC20/transfer_Other-Zero.iele.json

performance improvements to iele vm

---

Makefile

Fix path in Makefile

---

data.md
iele-gas.md
iele-node.md
iele.md

This is all the backwards-compatible fixes to get the llvm backend working with the iele mantis server.

more fixes for llvm backend

---

Makefile

fixes: https://github.com/runtimeverification/iele-semantics/issues/177

Build on Haskell backend

---

Makefile
iele-syntax.md
iele.md

fixes: https://github.com/runtimeverification/iog-pm/issues/22

Haskell build fix

---

web/build-html.js
web/static_content/html/page_template.html

Fixes: https://github.com/runtimeverification/web-common/issues/92

Add google analytics to documentation website

---

Jenkinsfile
web/package-lock.json
web/package.json
web/public_content/.gitignore
web/sitemap/build-sitemap.js

Fixes https://github.com/runtimeverification/web-common/issues/96

Add the sitemap generator

---

Jenkinsfile
Makefile
tests/iele/danse/ill-formed/duplicateFuncs.iele

fixes: https://github.com/runtimeverification/iog-pm/issues/50

Ill-formed checks

---

Jenkinsfile

Part of runtimeverification/iog-pm#51

Jenkinsfile: call auto-updater on successful deployment

---

.github/workflows/test.yml
Makefile
default.nix
kiele
nix/kiele.nix
nix/sources.json
test.nix

Fixes runtimeverification/iog-pm#56.

Add KIELE script to Nix package

---

assemble-iele-test

fixes: https://github.com/runtimeverification/iog-pm/issues/60

Call python2 for assemble-iele-test

---

Jenkinsfile
Makefile
kiele
tests/node-test.sh

fixes: https://github.com/runtimeverification/iog-pm/issues/61

Single `test` rule in Makefile for all tests

---

Makefile

fixes: https://github.com/runtimeverification/iog-pm/issues/62

Fix haskell backend install

---

.github/workflows/update.yml
default.nix
iele-assemble/default.nix
nix/kiele.nix
nix/libff.nix
nix/rematerialize.sh

Let's see if this solves the cache invalidation issue...

Automatically re-materialize Nix expressions

---

INSTALL.md

fixes: https://github.com/runtimeverification/iog-pm/issues/92

Update MacOS build instructions

---

kiele
kiele-generate-report.py

Basically we support to run the following commands to upload an Iele report to fireflyblockchain.com
```
export FIREFLY_TOKEN=QVlaYWN4cFE3NjJyNHhPcnBtclpCcHNuSmluUEZOcGwwcXVtalY0MGd0VT0=
export FIREFLY_ENDPOINT=http://127.0.0.1:8080
kiele upload reports.json
```
[reports.json.zip](https://github.com/runtimeverification/iele-semantics/files/6702314/reports.json.zip)

Support to upload Iele report to fireflyblockchain.com

---

Jenkinsfile

We were missing a bunch of `reuseNode` declarations.

Jenkinsfile: make sure were reusing nodes

---

INSTALL.md

Addresses this issue comment: https://github.com/runtimeverification/iog-pm/issues/54#issuecomment-880334282

Update Nix Install instructions

---

INSTALL.md

In addition to the opam command changes, I've fixed broken links as well as file paths that I've ran into while installing the iele-semantics

INSTALL.md: update installation directions
